name: geohashing
description: A new Flutter project.
version: 0.0.1
homepage: https://github.com/ruslanislan/geohashing

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  test: ^1.23.1

flutter:
